# permissions for end users to edit sevendays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sevendays-editor-role
rules:
- apiGroups:
  - game.laputacloud.co
  resources:
  - sevendays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.laputacloud.co
  resources:
  - sevendays/status
  verbs:
  - get
