# permissions for end users to view sevendays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sevendays-viewer-role
rules:
- apiGroups:
  - game.laputacloud.co
  resources:
  - sevendays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - game.laputacloud.co
  resources:
  - sevendays/status
  verbs:
  - get
