//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Laputa Cloud Co.

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SevenDays) DeepCopyInto(out *SevenDays) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SevenDays.
func (in *SevenDays) DeepCopy() *SevenDays {
	if in == nil {
		return nil
	}
	out := new(SevenDays)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SevenDays) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SevenDaysList) DeepCopyInto(out *SevenDaysList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SevenDays, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SevenDaysList.
func (in *SevenDaysList) DeepCopy() *SevenDaysList {
	if in == nil {
		return nil
	}
	out := new(SevenDaysList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SevenDaysList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SevenDaysSpec) DeepCopyInto(out *SevenDaysSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SevenDaysSpec.
func (in *SevenDaysSpec) DeepCopy() *SevenDaysSpec {
	if in == nil {
		return nil
	}
	out := new(SevenDaysSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SevenDaysStatus) DeepCopyInto(out *SevenDaysStatus) {
	*out = *in
	out.Cost = in.Cost.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SevenDaysStatus.
func (in *SevenDaysStatus) DeepCopy() *SevenDaysStatus {
	if in == nil {
		return nil
	}
	out := new(SevenDaysStatus)
	in.DeepCopyInto(out)
	return out
}
