---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 7dtd
  labels:
    app: 7dtd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 7dtd
  template:
    metadata:
      labels:
        app: 7dtd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - alpha
      containers:
        - name: server
          image: docker.io/didstopia/7dtd-server
          ports:
            - containerPort: 26900
              protocol: TCP
            - containerPort: 26900
              protocol: UDP
            - containerPort: 26901
              protocol: UDP
            - containerPort: 26902
              protocol: UDP
          env:
            - name: SEVEN_DAYS_TO_DIE_TELNET_PORT
              value: "8081"
            - name: SEVEN_DAYS_TO_DIE_TELNET_PASSWORD
              value: abc
          volumeMounts:
            - name: steamcmd
              mountPath: /steamcmd/7dtd
            - name: app
              mountPath: /app/.local/share/7DaysToDie
      # initContainers:
      #   - name: serverconfig
      #     image: docker.io/busybox:latest
      #     command:
      #       - sh
      #       - -c
      #       - cp /serverconfig.xml /app/.local/share/7DaysToDie/serverconfig.xml
      #     volumeMounts:
      #       - name: app
      #         mountPath: /app/.local/share/7DaysToDie
      #       - name: serverconfig
      #         mountPath: /serverconfig.xml
      #         subPath: serverconfig.xml
      volumes:
        - name: app
          persistentVolumeClaim:
            claimName: 7dtd-app
        - name: steamcmd
          persistentVolumeClaim:
            claimName: 7dtd-steamcmd
        - name: serverconfig
          configMap:
            name: serverconfig
