---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 7dtd-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 7dtd-steamcmd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 16Gi
